# Generated by Django 3.2.5 on 2021-09-07 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя категории')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('price', models.CharField(max_length=255, verbose_name='Цена продукта')),
                ('img', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dadova.category')),
            ],
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dadova.product')),
                ('rgb', models.BooleanField(default=True)),
                ('max_push_amount', models.CharField(max_length=255, verbose_name='Максимальное число нажатий')),
                ('material', models.CharField(max_length=255, verbose_name='Материал изготовления')),
            ],
            bases=('dadova.product',),
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dadova.product')),
                ('dpi', models.CharField(max_length=255, verbose_name='DPI')),
                ('max_click_amount', models.CharField(max_length=255, verbose_name='Максимальное число кликов')),
                ('material', models.CharField(max_length=255, verbose_name='Материал изготовления')),
            ],
            bases=('dadova.product',),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dadova.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(to='dadova.Product')),
            ],
        ),
    ]
